name: ğŸš€ Release Production

on:
  push:
    branches:
      - main

jobs:
  test:
    name: ğŸ§ª Run tests
    runs-on: ubuntu-latest
    outputs:
      react-email-changed: ${{ env.react-email-changed }}
      cli-changed: ${{ env.cli-changed }}

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: ğŸ“¦ Install dependencies
        run: bun install
      - name: ğŸ” Run type checking
        run: bun run typecheck
      # - name: ğŸ”¬ Run linting
      #   run: bun run lint
      - name: ğŸ§ª Run unit tests
        run: bun run test
      - name: Check package changes
        id: check-changes
        run: |
          npx changeset status > status.txt
          if grep -q 'packages/react-email' status.txt; then
            echo "react-email-changed=true" >> $GITHUB_ENV
          else
            echo "react-email-changed=false" >> $GITHUB_ENV
          fi
          if grep -q 'languine' status.txt; then
            echo "cli-changed=true" >> $GITHUB_ENV
          else
            echo "cli-changed=false" >> $GITHUB_ENV
          fi
    
  publish-cli:
    name: ğŸš€ Publish CLI
    needs: [test]
    runs-on: ubuntu-latest
    if: needs.test.outputs.cli-changed == 'true'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: ğŸ“¦ Install dependencies
        run: bun install
      - name: ğŸ—ï¸ Build
        working-directory: packages/cli
        run: bun run build
      - name: ğŸš€ Create and publish versions
        uses: changesets/action@master
        with:
          version: bun run changeset version
          commit: "chore: update versions"
          title: "chore: update versions"
          publish: bun run changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          
  publish-react-email:
    name: ğŸš€ Publish React Email
    needs: [test]
    runs-on: ubuntu-latest
    if: needs.test.outputs.react-email-changed == 'true'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: ğŸ“¦ Install dependencies
        run: bun install
      - name: ğŸ—ï¸ Build
        working-directory: packages/react-email
        run: bun run build
      - name: ğŸš€ Create and publish versions
        uses: changesets/action@master
        with:
          version: bun run changeset version
          commit: "chore: update versions"
          title: "chore: update versions"
          publish: bun run changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
