name: ğŸš€ Release Production

on:
  push:
    branches:
      - main

jobs:
  test:
    name: ğŸ§ª Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: ğŸ“¦ Install dependencies
        run: bun install
      - name: ğŸ” Run type checking
        run: bun run typecheck
      # - name: ğŸ”¬ Run linting
      #   run: bun run lint
      - name: ğŸ§ª Run unit tests
        run: bun run test
    
  publish-cli:
    name: ğŸš€ Publish CLI
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: ğŸ“¦ Install dependencies
        run: bun install
      - name: ğŸ—ï¸ Build
        working-directory: packages/cli
        run: bun run build
      - name: ğŸš€ Create and publish versions
        uses: changesets/action@master
        with:
          version: bun run changeset version
          commit: "chore: update versions"
          title: "chore: update versions"
          publish: bun run changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          
  publish-react-email:
    name: ğŸš€ Publish React Email
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: ğŸ“¦ Install dependencies
        run: bun install
      - name: ğŸ—ï¸ Build
        working-directory: packages/react-email
        run: bun run build
      - name: ğŸš€ Create and publish versions
        uses: changesets/action@master
        with:
          version: bun run changeset version
          commit: "chore: update versions"
          title: "chore: update versions"
          publish: bun run changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
