name: ğŸš€ Release Production

on:
  push:
    branches:
      - main

jobs:
  test:
    name: ğŸ§ª Run tests
    runs-on: ubuntu-latest
    outputs:
      react-email: ${{ steps.filter.outputs.react-email }}
      cli: ${{ steps.filter.outputs.cli }}

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: ğŸ“¦ Install dependencies
        run: bun install
      - name: ğŸ” Run type checking
        run: bun run typecheck
      # - name: ğŸ”¬ Run linting
      #   run: bun run lint
      - name: ğŸ§ª Run unit tests
        run: bun run test
      - name: ğŸ” Filter changes
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            react-email:
              - 'packages/react-email/src/**'
            cli:
              - 'packages/cli/src/**'

  publish-cli:
    name: ğŸš€ Publish CLI
    if: needs.test.outputs.cli == 'true'
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: ğŸ“¦ Install dependencies
        run: bun install
      - name: ğŸ—ï¸ Build
        working-directory: packages/cli
        run: bun run build
      - name: ğŸ”§ Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: ğŸ“ Create and publish versions
        working-directory: packages/cli
        run: |
          bunx changeset version
          git commit -am "chore: update versions"
          bunx changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          
  publish-react-email:
    name: ğŸš€ Publish React Email
    if: needs.test.outputs.react-email == 'true'
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: ğŸ“¦ Install dependencies
        run: bun install
      - name: ğŸ—ï¸ Build
        working-directory: packages/react-email
        run: bun run build
      - name: ğŸ”§ Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: ğŸ“ Create and publish versions
        working-directory: packages/react-email
        run: |
          bunx changeset version
          git commit -am "chore: update versions"
          bunx changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
